### ISSUE TITLE
Carousel on zoom so that all the images on the page can be seen

### ISSUE THREAD

**Issue by rajeevmyname** [HiDeoo/starlight-image-zoom#17]
### Is your feature request related to a problem?

It is painful to zoom every image on the page and then collapse it. Instead, when I zoom-in on one image, I would like to see all the images on the page using standard carousel navigation.

### Describe the solution you'd like

I would like carousel navigation on the image when it is zoomed so that previous and next images can be seen on the page.

**Comment by HiDeoo** [comment]
Thanks for your feedback 🙌

This plugin is close to what is usually called, afaik, the "Medium zoom" effect rather than the one you are referring to which would include a carousel of images. At the time being, I think I'm leaning towards keeping it that way and potentially let other plugins have different effects/behaviors/features.

Maybe [PhotoSwipe](https://photoswipe.com/) could be closer to what you are looking for, I know there is also a reference to use it with Astro: ["Astro + PhotoSwipe" guide](https://dev.to/petrovicz/astro-photoswipe-549a).
