### ISSUE TITLE
Make the image zoomable, based on the images size.

### ISSUE THREAD

**Issue by jonasfroeller** [HiDeoo/starlight-image-zoom#4]
### Is your feature request related to a problem?

I have a full page image. the problem is, that you can not see much, without zooming in.
That is why I hoped this plugin would change that, but If I click the image to open it in the lightbox, it overflows the container and is not readable, and the container is not scrollable. It would be good, to have a zoom, that is calculated by the size of the image, like the one in chrome. 
![image](https://github.com/HiDeoo/starlight-image-zoom/assets/121523551/92bfa9c3-0763-427f-93b7-580e3062f90b)

Overflow:
![image](https://github.com/HiDeoo/starlight-image-zoom/assets/121523551/632c6195-0eeb-4ade-b997-91d390c7aa95)

### Describe the solution you'd like

If i open the image url in another tab and zoom with chrome I get this result, which is what I hoped this plugin could do:
![image](https://github.com/HiDeoo/starlight-image-zoom/assets/121523551/c232c4a6-cd9b-4caa-ad0c-9d42c5e1dcc2)

### Describe alternatives you've considered

Writing my own plugin.

**Comment by HiDeoo** [comment]
Thanks for your feedback :raised_hands:

Indeed, this plugin is closer to what is usually called, afaik, the "Medium zoom" effect rather than the one you are referring to and I think I'm leaning towards keeping it that way. I may re-visit this in the future based on the feedback I get and maybe provide more options for the user to choose from (I think the original behavior would not change).

Regarding the effect you are referring to, I guess [PhotoSwipe](https://photoswipe.com/) would be closer to what you are looking for. If this is the case, I'm also linking some references for it with Astro: ["Astro + PhotoSwipe" guide](https://dev.to/petrovicz/astro-photoswipe-549a) and an [example repo](https://github.com/petrovicz/astro-photoswipe) of it.
