### ISSUE TITLE
太棒了，希望能集成swiperjs，图片放大后可以在本页所有图片中滑动切换，感谢辛苦付出！

### ISSUE THREAD

**Issue by hooziwang** [HiDeoo/starlight-image-zoom#6]
### Is your feature request related to a problem?

感谢辛苦付出哈！😄👏🏻🎆🎉🎉🎉🎉🎉🎉🎉

### Describe the solution you'd like

swiperjs实现的效果能集成进来就太完美了

**Comment by HiDeoo** [comment]
Thanks for your feedback.

As I mentioned in this [comment](https://github.com/HiDeoo/starlight-image-zoom/issues/4#issuecomment-2082620326), the current implementation is close to what I believe is called the simple "Medium zoom" effect and I'm leaning towards keeping it that way for now.
I think having different plugins for different use cases may be a better approach rather than trying to make a single plugin that fits all use cases, considering the complexity and accessibility challenges that may arise from supporting all use cases.

I may revisit this decision in the future based on feedback and usage patterns, but for now, I think it's best to keep it simple and focused on a single use case.
